#!/usr/bin/env bash
# A web server generating and serving HTML pages
# Update and install nginx
apt-get update
apt-get install -y nginx

# Create Hello World page
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx without using systemctl
service nginx restart

# Test Nginx
response=$(curl -sI localhost | grep HTTP/1.1 | awk {'print $2'})
if [ "$response" == "200" ]; then
    echo "Nginx is installed and configured successfully."
else
    echo "Error: Nginx installation or configuration issue."
fi
