#!/usr/bin/env bash
# Configures Nginx server to have a custom 404 page
# Define the configuration for the custom 404 page
ADD404_NOTFOUND="\n\tlocation / {\n\t\terror_page 404 /404.html;\n\t\tlocation = /404.html {\n\t\t\tinternal;\n\t\t\treturn 200 \"Ceci n'est pas une page\";\n\t\t}\n\t}"

# Update package lists and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set ownership for web directory
sudo chown -R ubuntu /var/www

# Create a default HTML page
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Add the configuration for the custom 404 page to Nginx configuration file
sudo sed -i "47i $ADD404_NOTFOUND" /etc/nginx/sites-available/default

# Restart and reload Nginx to apply changes
sudo service nginx restart
sudo service nginx reload
