#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create a custom configuration file
echo 'add_header X-Served-By $host;' | sudo tee /etc/nginx/sites-available/custom-header

# Create a symbolic link to the sites-enabled directory
sudo ln -s /etc/nginx/sites-available/custom-header /etc/nginx/sites-enabled/

# Remove default Nginx configuration
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
