#!/usr/bin/env bash
# A short and sweet fixing script
# Creates a symbolic-link of Nginx configuration and enabled sites directory"
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#Stars Nginx
service nginx start
# Terminates the first process
kill "$(pgrep 'nginx' head | -l)"

