#!/usr/bin/env bash
# This script displays a list of currently running processes.

printf "%-10s %-5s %-5s %-10s %-10s %-5s %-10s %-5s %-10s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "COMMAND"

ps aux | awk 'NR > 1 {printf "%-10s %-5s %-5s %-10s %-10s %-5s %-10s %-5s %-10s\n", $1, $2, $3, $4, $5, $6, $7, $8, $11}'
