#!/usr/bin/env bash
# Update nginx configuration to run as nginx user

sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update nginx default site configuration to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default

# Restart nginx service to apply changes
service nginx restart

# Verify nginx is running as nginx user and listening on port 8080
ps auxff | grep -E 'nginx: master process|nginx: worker process'
nc -z 0 8080 ; echo $?
