#!/usr/bin/env bash
pkill -f apache2
cp /etc/nginx/nginx.conf{,.bak}
cp /etc/nginx/sites-available/default{,.bak}
chown -R nginx:nginx /etc/nginx /usr/share/nginx
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's+pid /run/nginx.pid;+pid /tmp/nginx.pid;+' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
service nginx start
